### ISSUE TITLE
Total Contributors is invisible

### ISSUE THREAD

**Issue by im-adithya** [RocketChat/Opensource-Contribution-Leaderboard#68] opened 2021-01-26 14:43 UTC
The total number of contributors text is invisible.

![Screenshot (63)](https://user-images.githubusercontent.com/64399555/105859747-e30eae00-6012-11eb-8f4b-61478d55d746.png)

**Comment by RonLek** [comment] 2021-01-26 15:18
If I'm not wrong we did this to make an invisibile ranking available but I think we could show the total contributors while still keeping the ranking invisible. Wdyt @djcruz93 ?

**Comment by im-adithya** [comment] 2021-01-26 15:26
Oh! But I didn't get you exactly... Invisible ranking?

**Comment by RonLek** [comment] 2021-01-26 18:26
@im-adithya check [this](https://github.com/RocketChat/Opensource-Contribution-Leaderboard/issues/46) out

**Comment by im-adithya** [comment] 2021-01-26 18:30
@RonLek woah nice! 🙌
But this can be merged right as this has nothing to do with ranking and also total number of participants is usually part of a leaderboard especially when serial numbers aren't present...

**Comment by djcruz93** [comment] 2021-01-27 07:50
@im-adithya @RonLek We want the hidden text to remain hidden. This is NOT TO BOTHER the majority of the users- those who just check the leaderboard for their stats. It is only for the admins who just want to keep track of the number of contributors. 

@Sing-Li it will be great if you could please add to it.

**Comment by Sing-Li** [comment] 2021-01-28 03:50
I have nothing to add, well said.   It is *by design* to be hidden.

Thanks for your effort, but @im-adithya  we'll have to close this issue and the associated PR.

Please try to talk us and confirm before spending the energy on bug fixes next time.

**Closed by Sing-Li** 2021-01-28 03:50 UTC

**Comment by im-adithya** [comment] 2021-01-28 04:29
Sure @Sing-Li 😄
